### ISSUE TITLE
Move hard-coded values

### ISSUE THREAD

**Issue by misterveiga** [misterveiga/cds#12]
**Is your feature request related to a problem? Please describe.**
There are multiple instances of constant values located loosely in different classes.

**Describe the solution you'd like**
As an improvement to code quality, move these values, as well as any hard-coded values, to configuration files, i.e. properties file. Inject via Spring `@Value`. This will make maintenance, as well as new additions, easier.

**Additional context**
Sensitive data (API keys, etc) is already stored in environment variables and accessible via  `@Value` that points to an existing properties file in the project.

**Comment by Hassan-Elseoudy** [comment]
I'll be on it!

**Comment by misterveiga** [comment]
Awesome! Can't wait to see your contribution 😄
