### ISSUE TITLE
Automatically add z_approve reaction to all reports in mod-alerts

### ISSUE THREAD

**Issue by Visualizememe** [misterveiga/cds#50]
**The Issue**

Currently, it's a bit tedious to right-click a message (or hold on a phone), then press "add reaction" and if it's not in the first few results, you have to search for it. When there are a lot of requests, this can take some time, and it's quite tiresome.

In addition, some reports that have been handled are not removed because supervisors haven't added this reaction, and making it easier might solve that issue.

--

**My Solution**

RDSS should automatically react to all the report messages with z_approve, so that when we've handled a report it's just clicking one button and it's removed. Easy.

**Comment by liscuate** [comment]
Feature is now live in the bot.

**Comment by Visualizememe** [comment]
> Feature is now live in the bot.

Liscuate my man!
