### ISSUE TITLE
Automatically fetch amount of infractions after quick-mutes

### ISSUE THREAD

**Issue by Visualizememe** [misterveiga/cds#54]
**The Issue**
As quick-mutes makes it easier to forget checking a user's infractions, it can be forgotten and we should have RDSS automatically fetch the amount of infraction a user has, so it's easier for us to see if we should look deeper into their history.

**The Solution**
Fetch the user's infractions from RoSupervisor and if they have a considerable amount of infractions (>3 for example), it should mention that we may need to look further into the matter and take action.

**Consideration**
It can be difficult to parse the response from Rowboat properly and may take significant time to implement.

**Comment by misterveiga** [comment]
RDSS does not have access to the data source where RoSupervisor persists infraction history. There is no ideal way to retrieve information from RoSupervisor, so your proposed solution isn't viable.
It would be more convenient (given our use case) to create a MongoDB collection to persist historical data on user infractions, as well as implement methods defined in the existing `CdsData` interface to perform CRUD on this collection. We can also look at defining a data model for infractions.

I will close this issue so a new one can be created for this missing functionality.

**Comment by railworks2** [comment]
Would advise against MongoDB as it uses the SSPL[1] license which is a fauxpen[2] license which may cause issues in relation to using the current license for this project

[1] - https://www.mongodb.com/licensing/server-side-public-license
[2] - https://opensource.org/node/1099

**Comment by misterveiga** [comment]
MongoDB drivers are under Apache 2.0 as well as this project. https://www.mongodb.com/community/licensing
