### ISSUE TITLE
Allowing the quick_mute reactions to be used in mod-alerts.

### ISSUE THREAD

**Issue by liscuate** [misterveiga/cds#61]
When a Moderator reacts to a message in mod-alerts with either the qm_30 or qm_60, it will take action to the user and their message.

**Comment by liscuate** [comment]
With the message preview only being a short amount of the entire message, how would the reasoning for the quick mutes be?

**Comment by Phalanxia** [comment]
> With the message preview only being a short amount of the entire message, how would the reasoning for the quick mutes be?

@liscuate Would it be possible to grab the full content of the original message via the message link?
IE: https://discord.com/channels/150074202727251969/150074202727251969/849253585505484841

**Comment by liscuate** [comment]
> > With the message preview only being a short amount of the entire message, how would the reasoning for the quick mutes be?
> 
> @liscuate Would it be possible to grab the full content of the original message via the message link?
> IE: https://discord.com/channels/150074202727251969/150074202727251969/849253585505484841

That would actually be possible, yes. I will see if I can experiment with it.

**Comment by liscuate** [comment]
Implemented in b327153, now live in bot.
