### ISSUE TITLE
Message a user when they receive the "Muted" role

### ISSUE THREAD

**Issue by Phalanxia** [misterveiga/cds#65]
As a user, I may be unaware that I have been muted and may be confused due to my inability to view and interact in chat.

To solve this, we should DM users when they receive the "Muted" role. This message should match the message found in #muted, which importantly states that they were muted and what it means for them.

The message in #muted:
![image](https://user-images.githubusercontent.com/513906/120921147-2ccd6c00-c677-11eb-85ac-227cc863621f.png)

**Comment by TheMadKingNoah** [comment]
Ready to be tested

**Comment by TheMadKingNoah** [comment]
This has been completed and tested
