### ISSUE TITLE
Ban emoji in public channel creates ban-request

### ISSUE THREAD

**Issue by liscuate** [misterveiga/cds#73]
Having a reaction that when adding it to a message, it will automatically create a ban request in #ban-request-queue on behalf of the Moderator.

**Comment by TheMadKingNoah** [comment]
Problems:
-the ban request will be limited to only that specific message. There is no context and this would only make sense for bans such as racial slur bypassing
-The moderator will skip the process of going through their message history, will not search for the users previous infraction and will dive right into the ban.
