### ISSUE TITLE
Changing Duration/Reason Using Quick Mutes

### ISSUE THREAD

**Issue by liscuate** [misterveiga/cds#76]
**Describe the bug**
When a quick mute is handled and executed. The Moderator that used the Quick Mute reaction can not change the duration or reason of the mute.

**To Reproduce**
1: Mute a user using quick mutes.
2: Try changing the duration or reason.

**Expected behavior**
The Moderator that handed out the quick mute should be able to change the duration or reason.

**Current behavior**
The Moderator can't change the duration or reason.

**Comment by misterveiga** [comment]
Quick mutes are not designed in the same way that regular mutes are. You are not supposed to be able to change quick mute duration. If you believe the mute should be different from the predetermined values, you shouldn't be using quick mutes.
